---
abstract: 'a formatter for spellchecking Pod'
author:
  - 'Sean M. Burke <sburke@cpan.org>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Deep: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Spell
no_index:
  file:
    - perlcritic.rc
provides:
  Pod::Spell:
    file: lib/Pod/Spell.pm
    version: 1.03
  Pod::Wordlist:
    file: lib/Pod/Wordlist.pm
    version: 1.03
requires:
  Carp: 0
  Pod::Escapes: 0
  Pod::Parser: 0
  Text::Wrap: 0
  base: 0
  constant: 0
  locale: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/pod-spell/issues
  homepage: https://metacpan.org/dist/Pod-Spell
  repository: git://github.com/xenoterracide/pod-spell.git
version: 1.03
