
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::EOL 0.07
eval "use Test::EOL; 1;";
# ^^ hack to get around prereqscanner detection, remove someday

plan skip_all => "We require Test::EOL for this test." if $@;

all_perl_files_ok({ trailing_whitespace => 1 });
